name: Database Migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run migration'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
      migration_type:
        description: 'Type of migration'
        required: true
        default: 'migrate'
        type: choice
        options:
          - migrate
          - rollback
          - seed
          - reset

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd backend
        npm ci

    - name: Run Migration
      run: |
        cd backend
        case "${{ github.event.inputs.migration_type }}" in
          "migrate")
            npm run migrate
            ;;
          "rollback")
            npm run migrate:rollback
            ;;
          "seed")
            npm run seed
            ;;
          "reset")
            npm run migrate:reset
            ;;
        esac
      env:
        NODE_ENV: ${{ github.event.inputs.environment }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        REDIS_URL: ${{ secrets.REDIS_URL }}

    - name: Verify Migration
      run: |
        cd backend
        npm run migrate:status || echo "Migration status check completed"
      env:
        NODE_ENV: ${{ github.event.inputs.environment }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Notify Migration Success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        channel: '#deployments'
        text: '✅ Database migration completed successfully on ${{ github.event.inputs.environment }}'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify Migration Failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        channel: '#deployments'
        text: '❌ Database migration failed on ${{ github.event.inputs.environment }}'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}